#!/bin/sh

# Create Synopsys .lib file (has no area information yet)
alf2lib  -alf osu018_stdcells.alf -lib     osu018_stdcells_noarea.lib -def footprint.def

# Insert area information from .area file for library compiler
../../bin/osucells_mergearea -v "areafile=../../source/osu_stdcells.area" -v "l=0.10" osu018_stdcells_noarea.lib  > osu018_stdcells.lib

rm osu018_stdcells_noarea.lib

# Create a Verilog Simulation Library
alf2veri -alf osu018_stdcells.alf -verilog osu018_stdcells.v

# Create a VHDL Simulation Library
alf2vhdl -alf osu018_stdcells.alf -vhdl    osu018_stdcells.vhdl

# Create a Verilog cell definition library for Silicon Ensemble and add corner/vdd/gnd/nc cell definitions
rm osu018_stdcells.v.se
cat osu018_stdcells.v | awk '{if($1=="module"||(($1=="input"||$1=="output")&&$3==";")||$0=="endmodule") {print $0; if($0=="endmodule") {print ""}}}' > osu018_stdcells.v.se

lc_shell -f lc_script

/import/cadence2/ic50.33usr1/tools/bin/syn2tlf osu018_stdcells.lib  -ir 50 -if 50 -dr 50 -df 50 -sr 20 -sf 20 -tr 80 -tf 80 -slew_measure_lower_rise 20 -slew_measure_lower_fall 20 -slew_measure_upper_rise 80 -slew_measure_upper_fall 80 -o osu018_stdcells.tlf

/usr/bin/rm -rf ../html
alf2html -alf osu018_stdcells.alf -dir ../html
