#!/bin/sh

# Clean up
echo Cleaning up...
/usr/bin/rm -rf sigstormlc.log
/usr/bin/rm -rf sigstormlc.work
/usr/bin/rm -rf osu05_stdcells.ipdb

# Netlist the layouts
../../bin/osucells_netlist SCN3ME_SUBM.30 pads_ami05 osu05_stdcells.sp

# Run signalstorm
slc -S ss_step1

