deleteHaloFromBlock -allBlock
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_3_sram_voltage_island/i_3_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_0_sram_voltage_island/i_3_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_0_sram_voltage_island/i_0_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_2_sram_voltage_island/i_0_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_1_sram_voltage_island/i_0_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_2_sram_voltage_island/i_1_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_1_sram_voltage_island/i_1_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_2_sram_voltage_island/i_2_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_3_sram_voltage_island/i_1_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_2_sram_voltage_island/i_3_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_3_sram_voltage_island/i_0_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_sram_subsystem/i_3_sram_voltage_island/i_2_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 1 2 i_sram_subsystem/i_0_sram_voltage_island/i_1_SRAM_2kx32_wrap/i_sram_core 
addHaloToBlock 2 2 1 2 i_sram_subsystem/i_1_sram_voltage_island/i_2_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 1 2 2 2 i_sram_subsystem/i_0_sram_voltage_island/i_2_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 1 2 2 2 i_sram_subsystem/i_1_sram_voltage_island/i_3_SRAM_2kx32_wrap/i_sram_core
addHaloToBlock 2 2 2 2 i_D0TCM/i_sram_core_1 
addHaloToBlock 2 2 2 2 i_D1TCM/i_sram_core_1 
addHaloToBlock 2 2 2 2 i_D0TCM/i_sram_core_0 
addHaloToBlock 2 2 2 2 i_ITCM/i_sram_core 
addHaloToBlock 2 2 2 2 i_D1TCM/i_sram_core_0 
addHaloToBlock 2 2 8 2 i_Module_A
addHaloToBlock 2 2 2 2 i_Module_B
addHaloToBlock 2 2 2 2 i_Module_U
addHaloToBlock 2 2 2 2 i_Module_W
addHaloToBlock  1 1 1 1 i_rom_subsystem/i_rom_wrap/i_rom_core
addHaloToBlock 25 55 1 1 i_PLL
